"use client";

import { useCallback, useEffect, useState } from "react";
import { Download, FileUp, UserRoundCheck } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/lib/auth";
import { fetchEmployees, type EmployeeResponse } from "@/lib/api";
import { createRegularizationRecord, downloadRegularizationTemplate, effectRegularization, fetchRegularizationRecord, fetchRegularizationRecords, hrApprove, hrReject, importRegularization, postponeRegularization, supervisorApprove, supervisorReject, voidRegularization, type RegularizationRecord, type RegularizationSource, type RegularizationStatus } from "@/lib/api-regularization";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

const labels: Record<RegularizationStatus, string> = { pending_supervisor: "待上级审批", pending_hr_review: "待 HR 复核", scheduled: "已排期", postponed_scheduled: "延期排期", effective: "已生效", rejected: "已拒绝", effect_failed: "生效失败", cancelled_by_resignation: "因离职取消", voided: "已作废" };
type Action = "supervisor-approve" | "supervisor-reject" | "hr-approve" | "hr-reject" | "postpone" | "void" | "effect";
type ActionState = { type: Action; record: RegularizationRecord } | null;
const statusLabel = (status: string) => labels[status as RegularizationStatus] ?? "未知状态";
const isTrialEmployee = (item: EmployeeResponse) => item.status === "active" && (item as EmployeeResponse & { employment_status?: string }).employment_status === "trial";

export function RegularizationManagement() {
  const { user, hasPermission } = useAuth(); const canEdit = hasPermission("employee", "edit");
  const [records, setRecords] = useState<RegularizationRecord[]>([]); const [employees, setEmployees] = useState<EmployeeResponse[]>([]); const [status, setStatus] = useState<"all" | RegularizationStatus>("all"); const [source, setSource] = useState<"all" | RegularizationSource>("all"); const [loading, setLoading] = useState(true); const [createOpen, setCreateOpen] = useState(false); const [detail, setDetail] = useState<RegularizationRecord | null>(null); const [action, setAction] = useState<ActionState>(null); const [reason, setReason] = useState(""); const [comment, setComment] = useState(""); const [date, setDate] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const [list, staff] = await Promise.all([fetchRegularizationRecords(status === "all" ? undefined : status, source === "all" ? undefined : source), fetchEmployees()]); setRecords(list); setEmployees(staff); } catch (error) { toast.error(error instanceof Error ? error.message : "转正记录加载失败"); } finally { setLoading(false); } }, [source, status]);
  useEffect(() => { if (user && canEdit) void load(); }, [canEdit, load, user]);
  if (!user) return null;
  if (!canEdit) return <div className="mx-auto flex w-full max-w-4xl justify-center py-20"><Card className="w-full max-w-lg"><CardHeader><CardTitle>无转正管理权限</CardTitle><CardDescription>仅拥有员工编辑权限的用户可以查看和处理转正申请。</CardDescription></CardHeader></Card></div>;
  const runAction = async () => { if (!action) return; if (["supervisor-reject", "hr-reject", "postpone", "void"].includes(action.type) && !reason.trim()) return toast.error("原因必填"); if (action.type === "postpone" && !date) return toast.error("请选择新的计划转正日期"); try { const id = action.record.id; if (action.type === "supervisor-approve") await supervisorApprove(id, comment); if (action.type === "supervisor-reject") await supervisorReject(id, reason, comment); if (action.type === "hr-approve") await hrApprove(id, comment); if (action.type === "hr-reject") await hrReject(id, reason, comment); if (action.type === "postpone") await postponeRegularization(id, date, reason, comment); if (action.type === "void") await voidRegularization(id, reason); if (action.type === "effect") await effectRegularization(id); toast.success("操作成功，记录已刷新"); setAction(null); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "操作失败"); } };
  const showDetail = async (record: RegularizationRecord) => { try { setDetail(await fetchRegularizationRecord(record.id)); } catch (error) { toast.error(error instanceof Error ? error.message : "详情加载失败"); } };
  return <div className="mx-auto flex w-full max-w-7xl flex-col gap-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-muted-foreground">员工管理 / 转正管理</p><h1 className="text-3xl font-bold tracking-tight">转正管理</h1><p className="mt-1 text-muted-foreground">审批过程与员工快照均只读留存，不可覆盖。</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={downloadRegularizationTemplate}><Download className="mr-2 h-4 w-4" />Excel 模板</Button><ImportButton onImported={load} /><Button onClick={() => setCreateOpen(true)}><UserRoundCheck className="mr-2 h-4 w-4" />新申请</Button></div></header><Card><CardHeader className="gap-4 md:flex-row md:items-center md:justify-between"><div><CardTitle>转正记录</CardTitle><CardDescription>可按状态与来源筛选，点击查看完整审批时间线。</CardDescription></div><div className="flex gap-2"><select aria-label="状态筛选" value={status} onChange={(e) => setStatus(e.target.value as typeof status)} className="h-9 rounded-md border bg-background px-2 text-sm"><option value="all">全部状态</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="来源筛选" value={source} onChange={(e) => setSource(e.target.value as typeof source)} className="h-9 rounded-md border bg-background px-2 text-sm"><option value="all">全部来源</option><option value="manual">手工申请</option><option value="excel_direct">Excel 导入</option></select></div></CardHeader><CardContent>{loading ? <p className="py-12 text-center text-muted-foreground">正在加载转正记录…</p> : <RecordTable records={records} currentUserId={Number(user.id)} onDetail={showDetail} onAction={setAction} />}</CardContent></Card><CreateDialog open={createOpen} employees={employees.filter(isTrialEmployee)} initiatorId={Number(user.id)} onClose={() => setCreateOpen(false)} onSuccess={async (payload) => { await createRegularizationRecord(payload); toast.success("转正申请已提交"); setCreateOpen(false); await load(); }} /><DetailDialog record={detail} onClose={() => setDetail(null)} /><ActionDialog action={action} reason={reason} comment={comment} date={date} onClose={() => setAction(null)} onReason={setReason} onComment={setComment} onDate={setDate} onConfirm={runAction} /></div>;
}

function RecordTable({ records, currentUserId, onDetail, onAction }: { records: RegularizationRecord[]; currentUserId: number; onDetail: (record: RegularizationRecord) => void; onAction: (action: ActionState) => void }) { return records.length === 0 ? <p className="py-12 text-center text-muted-foreground">暂无转正记录</p> : <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="p-3">员工 / 编号</th><th className="p-3">部门 / 岗位</th><th className="p-3">计划日期</th><th className="p-3">状态</th><th className="p-3 text-right">操作</th></tr></thead><tbody>{records.map((record) => { const isSupervisor = record.supervisor_approver_user_id === currentUserId; const isHR = record.hr_reviewer_user_id === currentUserId; const isInitiator = record.initiator_hr_user_id === currentUserId; return <tr key={record.id} className="border-b last:border-0"><td className="p-3"><b>{record.snapshot_name}</b><p className="text-xs text-muted-foreground">{record.approval_no}</p></td><td className="p-3">{record.snapshot_department} / {record.snapshot_position}</td><td className="p-3 font-mono">{record.planned_regular_date}</td><td className="p-3"><span className="rounded-full bg-secondary px-2 py-1 text-xs">{statusLabel(record.status)}</span></td><td className="p-3"><div className="flex justify-end gap-1"><Button size="sm" variant="ghost" onClick={() => onDetail(record)}>详情</Button>{record.status === "pending_supervisor" && isSupervisor && <><Button size="sm" onClick={() => onAction({ type: "supervisor-approve", record })}>上级通过</Button><Button size="sm" variant="outline" onClick={() => onAction({ type: "supervisor-reject", record })}>上级拒绝</Button></>}{record.status === "pending_hr_review" && isHR && <><Button size="sm" onClick={() => onAction({ type: "hr-approve", record })}>HR 通过</Button><Button size="sm" variant="outline" onClick={() => onAction({ type: "hr-reject", record })}>HR 拒绝</Button><Button size="sm" variant="outline" onClick={() => onAction({ type: "postpone", record })}>延期</Button></>}{["scheduled", "postponed_scheduled"].includes(record.status) && isInitiator && <Button size="sm" onClick={() => onAction({ type: "effect", record })}>人工生效</Button>}{!["effective", "voided"].includes(record.status) && isInitiator && <Button size="sm" variant="ghost" onClick={() => onAction({ type: "void", record })}>作废</Button>}</div></td></tr>; })}</tbody></table></div>; }

function CreateDialog({ open, employees, initiatorId, onClose, onSuccess }: { open: boolean; employees: EmployeeResponse[]; initiatorId: number; onClose: () => void; onSuccess: (payload: Parameters<typeof createRegularizationRecord>[0]) => Promise<void> }) { const [employeeId, setEmployeeId] = useState(0); const [months, setMonths] = useState(12); const [supervisor, setSupervisor] = useState(""); const [reviewer, setReviewer] = useState(""); const [planned, setPlanned] = useState(""); const [review, setReview] = useState(""); const submit = async () => { const supervisorId = Number(supervisor); const reviewerId = Number(reviewer); if (!employeeId || !planned || months <= 0 || !supervisorId || !reviewerId) return toast.error("请填写员工、合同期限、计划日期、上级与 HR 用户 ID"); if (new Set([initiatorId, supervisorId, reviewerId]).size !== 3) return toast.error("发起人、直属上级、HR复核人必须为三名不同用户"); await onSuccess({ employee_id: employeeId, contract_term_months: months, employee_self_review: review, supervisor_approver_user_id: supervisorId, hr_reviewer_user_id: reviewerId, planned_regular_date: planned, probation_end_date: "" }); }; return <Dialog open={open} onOpenChange={(value) => !value && onClose()}><DialogContent><DialogHeader><DialogTitle>发起转正申请</DialogTitle><DialogDescription>当前没有用户列举接口，请输入同租户的直属上级和 HR 复核用户 ID。</DialogDescription></DialogHeader><div className="space-y-3"><Label>员工（仅在职试用期）<select aria-label="员工" className="mt-1 h-9 w-full rounded-md border bg-background px-2" value={employeeId} onChange={(e) => setEmployeeId(Number(e.target.value))}><option value="0">请选择员工</option>{employees.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.department || "未分配"}</option>)}</select></Label><Label>劳动合同期限（月）<Input type="number" min="1" value={months} onChange={(e) => setMonths(Number(e.target.value))} /></Label><Label>计划转正日期<Input type="date" value={planned} onChange={(e) => setPlanned(e.target.value)} /></Label><Label>直属上级用户 ID<Input value={supervisor} onChange={(e) => setSupervisor(e.target.value)} /></Label><Label>HR 复核用户 ID<Input value={reviewer} onChange={(e) => setReviewer(e.target.value)} /></Label><Label>员工自评（选填）<Textarea value={review} onChange={(e) => setReview(e.target.value)} /></Label></div><DialogFooter><Button variant="outline" onClick={onClose}>取消</Button><Button onClick={() => void submit()}>提交申请</Button></DialogFooter></DialogContent></Dialog>; }

function DetailDialog({ record, onClose }: { record: RegularizationRecord | null; onClose: () => void }) { const events = record ? [["发起", record.initiator_submitted_at], ["上级审批", record.supervisor_approved_at || record.supervisor_rejected_at], ["HR 复核", record.hr_reviewed_at], ["作废", record.voided_at]] : []; return <Dialog open={!!record} onOpenChange={(value) => !value && onClose()}><DialogContent><DialogHeader><DialogTitle>转正详情与不可变快照</DialogTitle><DialogDescription>员工快照和审批历史由服务端留存，只读展示。</DialogDescription></DialogHeader>{record && <div className="space-y-3 text-sm"><p><b>{record.snapshot_name}</b> · {record.snapshot_department} / {record.snapshot_position}</p><p>试用期结束：{record.snapshot_probation_end_date || "未记录"}；合同期限：{record.contract_term_months} 个月</p><p>自评：{record.employee_self_review || "未填写"}</p><div className="border-l pl-4">{events.filter(([, at]) => at).map(([label, at]) => <p key={label}><b>{label}</b>：{String(at).slice(0, 19)}</p>)}</div></div>}</DialogContent></Dialog>; }
function ActionDialog({ action, reason, comment, date, onClose, onReason, onComment, onDate, onConfirm }: { action: ActionState; reason: string; comment: string; date: string; onClose: () => void; onReason: (value: string) => void; onComment: (value: string) => void; onDate: (value: string) => void; onConfirm: () => void }) { const needsReason = !!action && ["supervisor-reject", "hr-reject", "postpone", "void"].includes(action.type); return <Dialog open={!!action} onOpenChange={(value) => !value && onClose()}><DialogContent><DialogHeader><DialogTitle>确认提交操作</DialogTitle><DialogDescription>此操作将提交至服务端并刷新记录，请确认后继续。</DialogDescription></DialogHeader>{action?.type === "postpone" && <Label>新计划转正日期<Input type="date" value={date} onChange={(e) => onDate(e.target.value)} /></Label>}{needsReason && <Label>原因 *<Textarea value={reason} onChange={(e) => onReason(e.target.value)} /></Label>}{action?.type !== "void" && <Label>审批意见（选填）<Textarea value={comment} onChange={(e) => onComment(e.target.value)} /></Label>}<DialogFooter><Button variant="outline" onClick={onClose}>取消</Button><Button onClick={onConfirm}>确认提交</Button></DialogFooter></DialogContent></Dialog>; }
function ImportButton({ onImported }: { onImported: () => Promise<void> }) { const [feedback, setFeedback] = useState<{ warnings: { row: number; reason: string }[]; errors: { row: number; reason: string }[] } | null>(null); const upload = async (file?: File) => { if (!file) return; try { const result = await importRegularization(file); setFeedback(result); if (result.errors.length) toast.error("整文件校验未通过，未导入任何记录"); else { toast.success(`成功导入 ${result.imported ?? 0} 条记录`); await onImported(); } } catch (error) { toast.error(error instanceof Error ? error.message : "导入失败"); } }; return <div><Label className="inline-flex h-9 cursor-pointer items-center rounded-md border px-3 text-sm"><FileUp className="mr-2 h-4 w-4" />导入 Excel<input aria-label="导入 Excel" className="sr-only" type="file" accept=".xlsx" onChange={(e) => void upload(e.target.files?.[0])} /></Label>{feedback && <div className="mt-2 max-w-sm text-xs"><p className="text-muted-foreground">整文件校验；未来日期将排期，上海时间 02:00 后到期记录可人工生效。</p>{feedback.warnings.map((item) => <p key={`w${item.row}`} className="text-amber-700">警告 第 {item.row} 行：{item.reason}</p>)}{feedback.errors.map((item) => <p key={`e${item.row}`} className="text-destructive">错误 第 {item.row} 行：{item.reason}</p>)}</div>}</div>; }
