"use client";

import { useCallback, useEffect, useState } from "react";
import { ClipboardCheck, CheckCircle2, Pencil, Trash2, XCircle } from "lucide-react";
import { toast } from "sonner";

import { completeSafetyInspection, createSafetyInspection, deleteSafetyInspection, fetchSafetyInspections, updateSafetyInspection, voidSafetyInspection, type SafetyInspectionPayload, type SafetyInspectionRecord, type SafetyInspectionStatus, type SafetyInspectionType } from "@/lib/api-safety-inspections";
import { useAuth } from "@/lib/auth";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

const STATUS_LABELS: Record<SafetyInspectionStatus, string> = { draft: "草稿", completed: "已完成", voided: "已作废" };
const TYPE_LABELS: Record<SafetyInspectionType, string> = { routine: "例行检查", special: "专项检查" };
const STATUS_OPTIONS: Array<"all" | SafetyInspectionStatus> = ["all", "draft", "completed", "voided"];

export function SafetyManagement() {
  const { user, hasPermission } = useAuth();
  const canView = hasPermission("safety", "view");
  const canCreate = hasPermission("safety", "create");
  const canEdit = hasPermission("safety", "edit");
  const canDelete = hasPermission("safety", "delete");
  const [records, setRecords] = useState<SafetyInspectionRecord[]>([]);
  const [status, setStatus] = useState<"all" | SafetyInspectionStatus>("all");
  const [editing, setEditing] = useState<SafetyInspectionRecord | null | false>(false);
  const [voiding, setVoiding] = useState<SafetyInspectionRecord | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { setRecords(await fetchSafetyInspections(status === "all" ? undefined : status)); } catch (error) { toast.error(error instanceof Error ? error.message : "安全检查加载失败"); } finally { setLoading(false); } }, [status]);
  useEffect(() => { if (user && canView) void load(); }, [canView, load, user]);
  const runAction = async (action: () => Promise<unknown>, success: string, failure: string) => { setBusy(true); try { await action(); toast.success(success); await load(); return true; } catch (error) { toast.error(error instanceof Error ? error.message : failure); return false; } finally { setBusy(false); } };
  if (!user) return null;
  if (!canView) return <NoPermission />;
  return <div className="mx-auto flex w-full max-w-7xl flex-col gap-6">
    <header className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-indigo-950 to-blue-900 px-6 py-7 text-white shadow-xl"><div className="absolute -right-8 -top-12 h-40 w-40 rounded-full bg-blue-300/20 blur-3xl" /><div className="relative flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-blue-100">行政管理 / 安全管理</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">安全管理</h1><p className="mt-2 max-w-xl text-sm text-blue-50/80">独立安全检查台账，记录检查问题与整改要求。</p></div>{canCreate && <Button className="bg-white text-blue-950 hover:bg-blue-50" onClick={() => setEditing(null)}><ClipboardCheck className="mr-2 h-4 w-4" />新建安全检查</Button>}</div></header>
    <Card><CardHeader className="gap-4 md:flex-row md:items-center md:justify-between"><div><CardTitle>安全检查台账</CardTitle><CardDescription>草稿可编辑或完成；草稿和已完成记录均可填写原因作废。</CardDescription></div><div className="flex flex-wrap gap-2" aria-label="安全检查状态筛选">{STATUS_OPTIONS.map((item) => <Button key={item} size="sm" variant={status === item ? "default" : "outline"} onClick={() => setStatus(item)}>{item === "all" ? "全部" : STATUS_LABELS[item]}</Button>)}</div></CardHeader><CardContent>{loading ? <p className="py-12 text-center text-sm text-muted-foreground">正在加载安全检查台账…</p> : <InspectionTable records={records} canEdit={canEdit} canDelete={canDelete} onEdit={setEditing} onComplete={(id) => void runAction(() => completeSafetyInspection(id), "安全检查已完成", "安全检查完成失败")} onDelete={(id) => void runAction(() => deleteSafetyInspection(id), "安全检查草稿已删除", "安全检查草稿删除失败")} onVoid={setVoiding} />}</CardContent></Card>
    <InspectionDialog record={editing} busy={busy} onClose={() => setEditing(false)} onSubmit={async (payload) => { const succeeded = await runAction(() => editing ? updateSafetyInspection(editing.id, payload) : createSafetyInspection(payload), editing ? "安全检查草稿已更新" : "安全检查草稿已创建", "安全检查保存失败"); if (succeeded) setEditing(false); }} />
    <VoidDialog record={voiding} busy={busy} onClose={() => setVoiding(null)} onSubmit={async (reason) => { if (!voiding) return; const succeeded = await runAction(() => voidSafetyInspection(voiding.id, reason), "安全检查已作废", "安全检查作废失败"); if (succeeded) setVoiding(null); }} />
  </div>;
}

function NoPermission() { return <Card className="mx-auto mt-16 max-w-lg"><CardHeader><CardTitle>无安全管理查看权限</CardTitle><CardDescription>请联系管理员申请 safety.view 权限。</CardDescription></CardHeader></Card>; }
function InspectionTable({ records, canEdit, canDelete, onEdit, onComplete, onDelete, onVoid }: { records: SafetyInspectionRecord[]; canEdit: boolean; canDelete: boolean; onEdit: (record: SafetyInspectionRecord) => void; onComplete: (id: number) => void; onDelete: (id: number) => void; onVoid: (record: SafetyInspectionRecord) => void }) { if (!records.length) return <div className="py-12 text-center"><ClipboardCheck className="mx-auto mb-3 h-9 w-9 text-muted-foreground" /><p className="font-medium">暂无安全检查记录</p><p className="mt-1 text-sm text-muted-foreground">从新建一条安全检查记录开始。</p></div>; return <div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="p-3">检查类型</th><th className="p-3">检查日期 / 地点</th><th className="p-3">负责人</th><th className="p-3">问题描述</th><th className="p-3">整改要求</th><th className="p-3">状态</th><th className="p-3 text-right">操作</th></tr></thead><tbody>{records.map((record) => <tr key={record.id} className="border-b last:border-0"><td className="p-3 font-medium">{TYPE_LABELS[record.inspection_type]}</td><td className="p-3"><p className="font-mono">{record.inspection_date}</p><p className="text-xs text-muted-foreground">{record.location}</p></td><td className="p-3">{record.responsible_person}</td><td className="max-w-xs p-3"><p className="line-clamp-2">{record.issue_description}</p></td><td className="max-w-xs p-3"><p className="line-clamp-2">{record.rectification_requirement}</p></td><td className="p-3"><span className="rounded-full bg-secondary px-2.5 py-1 text-xs font-medium">{STATUS_LABELS[record.status]}</span></td><td className="p-3"><div className="flex justify-end gap-1">{record.status === "draft" && canEdit && <><Button size="sm" variant="ghost" onClick={() => onEdit(record)}><Pencil className="mr-1 h-4 w-4" />编辑</Button><Button size="sm" variant="ghost" onClick={() => onComplete(record.id)}><CheckCircle2 className="mr-1 h-4 w-4" />完成</Button></>}{record.status === "draft" && canDelete && <Button size="sm" variant="ghost" className="text-destructive" onClick={() => onDelete(record.id)}><Trash2 className="mr-1 h-4 w-4" />删除</Button>}{(record.status === "draft" || record.status === "completed") && canDelete && <Button size="sm" variant="ghost" className="text-destructive" onClick={() => onVoid(record)}><XCircle className="mr-1 h-4 w-4" />作废</Button>}</div></td></tr>)}</tbody></table></div>; }
function InspectionDialog({ record, busy, onClose, onSubmit }: { record: SafetyInspectionRecord | null | false; busy: boolean; onClose: () => void; onSubmit: (payload: SafetyInspectionPayload) => Promise<void> }) { const [form, setForm] = useState<SafetyInspectionPayload>(emptyPayload()); useEffect(() => setForm(record ? { inspection_type: record.inspection_type, inspection_date: record.inspection_date, location: record.location, responsible_person: record.responsible_person, issue_description: record.issue_description, rectification_requirement: record.rectification_requirement } : emptyPayload()), [record]); const update = (key: Exclude<keyof SafetyInspectionPayload, "inspection_type">, value: string) => setForm((current) => ({ ...current, [key]: value })); const submit = () => { if (!form.inspection_date || !form.location.trim() || !form.responsible_person.trim() || !form.issue_description.trim() || !form.rectification_requirement.trim()) return toast.error("请填写检查类型、检查日期、检查地点、负责人、问题描述和整改要求"); return onSubmit(form); }; return <Dialog open={record !== false} onOpenChange={(open) => !open && onClose()}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>{record ? "编辑安全检查草稿" : "新建安全检查"}</DialogTitle><DialogDescription>安全检查独立留存；不包含隐患分派、审批或附件流程。</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><Label>检查类型 *<select aria-label="检查类型" className="mt-1 h-9 w-full rounded-md border bg-background px-2" value={form.inspection_type} onChange={(event) => setForm((current) => ({ ...current, inspection_type: event.target.value as SafetyInspectionType }))}><option value="routine">例行检查</option><option value="special">专项检查</option></select></Label><Field label="检查日期 *" type="date" value={form.inspection_date} onChange={(value) => update("inspection_date", value)} /><Field label="检查地点 *" value={form.location} onChange={(value) => update("location", value)} /><Field label="负责人 *" value={form.responsible_person} onChange={(value) => update("responsible_person", value)} /><Label className="sm:col-span-2">问题描述 *<Textarea aria-label="问题描述" className="mt-1" value={form.issue_description} onChange={(event) => update("issue_description", event.target.value)} /></Label><Label className="sm:col-span-2">整改要求 *<Textarea aria-label="整改要求" className="mt-1" value={form.rectification_requirement} onChange={(event) => update("rectification_requirement", event.target.value)} /></Label></div><DialogFooter><Button variant="outline" onClick={onClose}>取消</Button><Button disabled={busy} onClick={submit}>保存草稿</Button></DialogFooter></DialogContent></Dialog>; }
function Field({ label, value, type = "text", onChange }: { label: string; value: string; type?: string; onChange: (value: string) => void }) { return <Label>{label}<Input className="mt-1" type={type} value={value} onChange={(event) => onChange(event.target.value)} /></Label>; }
function emptyPayload(): SafetyInspectionPayload { return { inspection_type: "routine", inspection_date: "", location: "", responsible_person: "", issue_description: "", rectification_requirement: "" }; }
function VoidDialog({ record, busy, onClose, onSubmit }: { record: SafetyInspectionRecord | null; busy: boolean; onClose: () => void; onSubmit: (reason: string) => Promise<void> }) { const [reason, setReason] = useState(""); useEffect(() => setReason(""), [record]); return <Dialog open={record !== null} onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>作废安全检查</DialogTitle><DialogDescription>作废只影响安全检查台账。</DialogDescription></DialogHeader><Label>作废原因 *<Textarea className="mt-1" value={reason} onChange={(event) => setReason(event.target.value)} /></Label><DialogFooter><Button variant="outline" onClick={onClose}>取消</Button><Button variant="destructive" disabled={busy} onClick={() => reason.trim() ? onSubmit(reason) : toast.error("作废原因必填")}>确认作废</Button></DialogFooter></DialogContent></Dialog>; }
